MGF-167-feat(behaviour update): internship_application: entreprise data  available from employer validation time
betagouv/monstagedeseconde pull request #112
Opened 2024-03-18 13:57 UTC by fitchMitch

2024-03-18 16:06 UTC, pierrax requested changes

2024-03-18 16:06 UTC, pierrax commented on app/components/application_component.rb
> +  # url : http://localhost:3000/rails/view_components/
on a besoin de ça ?

2024-03-18 16:26 UTC, fitchMitch commented on app/components/application_component.rb
> +  # url : http://localhost:3000/rails/view_components/
moi, je cherche de temps en temps pour faire des tests et je mets du temps à retrouver, ça peut être bien de le documenter quelque part .... où  ??

2024-03-20 13:37 UTC, pierrax approved these changes

2024-03-20 14:58 UTC, merged